import Head from 'next/head'
import Image from 'next/image'
import HomePage from './../Page/HomePage/index';
import Layout from './../components/Layout/index';

export default function Home() {
  return (
    <div>
      <Head>
        <title>One Love</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>

      <HomePage/>
      </Layout>
    </div>
  )
}
